/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAdministracaoRouteImport } from './routes/app.administracao'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'
import { Route as AppAgendamentosRouteImport } from './routes/app.agendamentos'
import { Route as AppAtendimentosRouteImport } from './routes/app.atendimentos'
import { Route as AppBemEstarRouteImport } from './routes/app.bem-estar'
import { Route as AppCampanhasRouteImport } from './routes/app.campanhas'
import { Route as AppConteudosRouteImport } from './routes/app.conteudos'
import { Route as AppIndicadoresRouteImport } from './routes/app.indicadores'
import { Route as AppPerfilRouteImport } from './routes/app.perfil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdministracaoRoute = AppAdministracaoRouteImport.update({
  id: '/administracao',
  path: '/administracao',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendamentosRoute = AppAgendamentosRouteImport.update({
  id: '/agendamentos',
  path: '/agendamentos',
  getParentRoute: () => AppRoute,
} as any)
const AppAtendimentosRoute = AppAtendimentosRouteImport.update({
  id: '/atendimentos',
  path: '/atendimentos',
  getParentRoute: () => AppRoute,
} as any)
const AppBemEstarRoute = AppBemEstarRouteImport.update({
  id: '/bem-estar',
  path: '/bem-estar',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhasRoute = AppCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AppRoute,
} as any)
const AppConteudosRoute = AppConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => AppRoute,
} as any)
const AppIndicadoresRoute = AppIndicadoresRouteImport.update({
  id: '/indicadores',
  path: '/indicadores',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/administracao': typeof AppAdministracaoRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/agendamentos': typeof AppAgendamentosRoute
  '/app/atendimentos': typeof AppAtendimentosRoute
  '/app/bem-estar': typeof AppBemEstarRoute
  '/app/campanhas': typeof AppCampanhasRoute
  '/app/conteudos': typeof AppConteudosRoute
  '/app/indicadores': typeof AppIndicadoresRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/administracao': typeof AppAdministracaoRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/agendamentos': typeof AppAgendamentosRoute
  '/app/atendimentos': typeof AppAtendimentosRoute
  '/app/bem-estar': typeof AppBemEstarRoute
  '/app/campanhas': typeof AppCampanhasRoute
  '/app/conteudos': typeof AppConteudosRoute
  '/app/indicadores': typeof AppIndicadoresRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/administracao': typeof AppAdministracaoRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/agendamentos': typeof AppAgendamentosRoute
  '/app/atendimentos': typeof AppAtendimentosRoute
  '/app/bem-estar': typeof AppBemEstarRoute
  '/app/campanhas': typeof AppCampanhasRoute
  '/app/conteudos': typeof AppConteudosRoute
  '/app/indicadores': typeof AppIndicadoresRoute
  '/app/perfil': typeof AppPerfilRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/administracao'
    | '/app/agenda'
    | '/app/agendamentos'
    | '/app/atendimentos'
    | '/app/bem-estar'
    | '/app/campanhas'
    | '/app/conteudos'
    | '/app/indicadores'
    | '/app/perfil'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/administracao'
    | '/app/agenda'
    | '/app/agendamentos'
    | '/app/atendimentos'
    | '/app/bem-estar'
    | '/app/campanhas'
    | '/app/conteudos'
    | '/app/indicadores'
    | '/app/perfil'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/administracao'
    | '/app/agenda'
    | '/app/agendamentos'
    | '/app/atendimentos'
    | '/app/bem-estar'
    | '/app/campanhas'
    | '/app/conteudos'
    | '/app/indicadores'
    | '/app/perfil'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/administracao': {
      id: '/app/administracao'
      path: '/administracao'
      fullPath: '/app/administracao'
      preLoaderRoute: typeof AppAdministracaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agendamentos': {
      id: '/app/agendamentos'
      path: '/agendamentos'
      fullPath: '/app/agendamentos'
      preLoaderRoute: typeof AppAgendamentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/atendimentos': {
      id: '/app/atendimentos'
      path: '/atendimentos'
      fullPath: '/app/atendimentos'
      preLoaderRoute: typeof AppAtendimentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/bem-estar': {
      id: '/app/bem-estar'
      path: '/bem-estar'
      fullPath: '/app/bem-estar'
      preLoaderRoute: typeof AppBemEstarRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/campanhas': {
      id: '/app/campanhas'
      path: '/campanhas'
      fullPath: '/app/campanhas'
      preLoaderRoute: typeof AppCampanhasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/conteudos': {
      id: '/app/conteudos'
      path: '/conteudos'
      fullPath: '/app/conteudos'
      preLoaderRoute: typeof AppConteudosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/indicadores': {
      id: '/app/indicadores'
      path: '/indicadores'
      fullPath: '/app/indicadores'
      preLoaderRoute: typeof AppIndicadoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/perfil': {
      id: '/app/perfil'
      path: '/perfil'
      fullPath: '/app/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdministracaoRoute: typeof AppAdministracaoRoute
  AppAgendaRoute: typeof AppAgendaRoute
  AppAgendamentosRoute: typeof AppAgendamentosRoute
  AppAtendimentosRoute: typeof AppAtendimentosRoute
  AppBemEstarRoute: typeof AppBemEstarRoute
  AppCampanhasRoute: typeof AppCampanhasRoute
  AppConteudosRoute: typeof AppConteudosRoute
  AppIndicadoresRoute: typeof AppIndicadoresRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdministracaoRoute: AppAdministracaoRoute,
  AppAgendaRoute: AppAgendaRoute,
  AppAgendamentosRoute: AppAgendamentosRoute,
  AppAtendimentosRoute: AppAtendimentosRoute,
  AppBemEstarRoute: AppBemEstarRoute,
  AppCampanhasRoute: AppCampanhasRoute,
  AppConteudosRoute: AppConteudosRoute,
  AppIndicadoresRoute: AppIndicadoresRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
